"""add password_expires_at

Revision ID: 6eb7e76d0b08
Revises: f2e6ee9a8b7d
Create Date: 2026-05-16 20:59:51.455540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb7e76d0b08'
down_revision: Union[str, None] = 'f2e6ee9a8b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.drop_index('ix_tenants_stripe_customer_id', table_name='tenants')
    op.drop_index('ix_tenants_stripe_subscription_id', table_name='tenants')
    op.create_index(op.f('ix_public_tenants_slug'), 'tenants', ['slug'], unique=True, schema='public')
    op.create_index(op.f('ix_public_tenants_stripe_customer_id'), 'tenants', ['stripe_customer_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_tenants_stripe_subscription_id'), 'tenants', ['stripe_subscription_id'], unique=True, schema='public')
    op.add_column('users', sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True, schema='public')
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'password_expires_at')
    op.drop_index(op.f('ix_public_tenants_stripe_subscription_id'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_stripe_customer_id'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_slug'), table_name='tenants', schema='public')
    op.create_index('ix_tenants_stripe_subscription_id', 'tenants', ['stripe_subscription_id'], unique=True)
    op.create_index('ix_tenants_stripe_customer_id', 'tenants', ['stripe_customer_id'], unique=True)
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###
