"""add image_url to products

Revision ID: b246ab9fc2cd
Revises: 3d7b5b32c84f
Create Date: 2026-05-12 01:44:34.014447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b246ab9fc2cd'
down_revision: Union[str, None] = '3d7b5b32c84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_products_ean', table_name='products')
    op.drop_index('ix_products_sku_filho', table_name='products')
    op.drop_index('ix_products_sku_pai', table_name='products')
    op.drop_constraint('products_tenant_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_parent_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'products', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_parent_id_fkey', 'products', 'products', ['parent_id'], ['id'])
    op.create_foreign_key('products_tenant_id_fkey', 'products', 'tenants', ['tenant_id'], ['id'])
    op.create_index('ix_products_sku_pai', 'products', ['sku_pai'], unique=False)
    op.create_index('ix_products_sku_filho', 'products', ['sku_filho'], unique=False)
    op.create_index('ix_products_ean', 'products', ['ean'], unique=False)
    op.alter_column('products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
