"""add soft delete and historical tracking to products

Revision ID: e1dbce0da550
Revises: 88c020edcd66
Create Date: 2026-05-12 05:01:22.020584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1dbce0da550'
down_revision: Union[str, None] = '88c020edcd66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('last_deleted_by', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('deactivation_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['last_deleted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'deactivation_count')
    op.drop_column('products', 'last_deleted_by')
    op.drop_column('products', 'deleted_at')
    # ### end Alembic commands ###
